spring:
  application:
    name: matchapi
  datasource:
    url: jdbc:postgresql://localhost:5432/matchdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
